# Generated by Django 2.0.2 on 2018-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180226_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='pics/none.jpg', upload_to=''),
        ),
    ]
